--comment: Добавление автобрендов

INSERT INTO auto_car_brands (brand) VALUES ('Toyota');
INSERT INTO auto_car_brands (brand) VALUES ('Ford');
INSERT INTO auto_car_brands (brand) VALUES ('Chevrolet');
INSERT INTO auto_car_brands (brand) VALUES ('Nissan');
INSERT INTO auto_car_brands (brand) VALUES ('Hyundai');
INSERT INTO auto_car_brands (brand) VALUES ('KIA');
INSERT INTO auto_car_brands (brand) VALUES ('Mercedes-Benz');
INSERT INTO auto_car_brands (brand) VALUES ('BMW');
INSERT INTO auto_car_brands (brand) VALUES ('Opel');
INSERT INTO auto_car_brands (brand) VALUES ('Mazda');
INSERT INTO auto_car_brands (brand) VALUES ('Acura');
INSERT INTO auto_car_brands (brand) VALUES ('Volkswagen');
INSERT INTO auto_car_brands (brand) VALUES ('Citroen');
INSERT INTO auto_car_brands (brand) VALUES ('Volvo');
INSERT INTO auto_car_brands (brand) VALUES ('Skoda');
INSERT INTO auto_car_brands (brand) VALUES ('Land Rover');
INSERT INTO auto_car_brands (brand) VALUES ('Renault');
INSERT INTO auto_car_brands (brand) VALUES ('Honda');
INSERT INTO auto_car_brands (brand) VALUES ('Datsun');
INSERT INTO auto_car_brands (brand) VALUES ('Mitsubishi');
INSERT INTO auto_car_brands (brand) VALUES ('Audi');
INSERT INTO auto_car_brands (brand) VALUES ('Jeep');
INSERT INTO auto_car_brands (brand) VALUES ('LADA');
INSERT INTO auto_car_brands (brand) VALUES ('УАЗ');
INSERT INTO auto_car_brands (brand) VALUES ('Peugeot');
INSERT INTO auto_car_brands (brand) VALUES ('Daewoo');
INSERT INTO auto_car_brands (brand) VALUES ('SsangYong');
INSERT INTO auto_car_brands (brand) VALUES ('Lexus');
INSERT INTO auto_car_brands (brand) VALUES ('Subaru');
INSERT INTO auto_car_brands (brand) VALUES ('Suzuki');
INSERT INTO auto_car_brands (brand) VALUES ('Infiniti');
INSERT INTO auto_car_brands (brand) VALUES ('Chery');
INSERT INTO auto_car_brands (brand) VALUES ('Geely');
INSERT INTO auto_car_brands (brand) VALUES ('Great Wall');
INSERT INTO auto_car_brands (brand) VALUES ('Brilliance');
INSERT INTO auto_car_brands (brand) VALUES ('Lifan');
INSERT INTO auto_car_brands (brand) VALUES ('Haima');
