ALTER TABLE auto_cars DROP COLUMN name;
ALTER TABLE auto_cars ADD COLUMN brand_id INT NOT NULL REFERENCES auto_car_brands(id);
ALTER TABLE auto_cars ADD COLUMN color VARCHAR(20) NOT NULL;
ALTER TABLE auto_cars ADD COLUMN model_year CHAR(4) NOT NULL;
ALTER TABLE auto_cars ADD COLUMN mileage VARCHAR(6) NOT NULL;